[package]
name = "srp"
version = "0.7.0-pre.0"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "Secure Remote Password (SRP) protocol implementation"
documentation = "https://docs.rs/srp"
repository = "https://github.com/RustCrypto/PAKEs"
keywords = ["crypto", "pake", "authentication"]
categories = ["cryptography", "authentication"]
readme = "README.md"
edition = "2024"
rust-version = "1.85"

[dependencies]
num-bigint = "0.4"
digest = "0.11.0-rc.5"
lazy_static = "1.2"
subtle = "2.4"

[dev-dependencies]
getrandom = { version = "0.4.0-rc.0", features = ["sys_rng"] }
hex-literal = "1"
num-traits = "0.2"
sha1 = "0.11.0-rc.3"
sha2 = "0.11.0-rc.3"
