[package]
name = "srp"
version = "0.4.3"
edition = "2018"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "Secure Remote Password (SRP) protocol implementation"
documentation = "https://docs.rs/srp"
repository = "https://github.com/RustCrypto/PAKEs"
keywords = ["crypto", "pake", "authentication"]
categories = ["cryptography", "authentication"]

[dependencies]
num-bigint = "0.2"
generic-array = "0.12"
digest = "0.8"
lazy_static = "1.2"

[dev-dependencies]
rand_core = { version = "0.5", default-features = false, features = ["getrandom"] }
sha2 = "0.8"
sha-1 = "0.8"

[badges]
travis-ci = { repository = "RustCrypto/PAKEs" }
