[workspace]
resolver = "2"
members = [
    "aucpace",
    "spake2",
    "srp",
]

[profile.dev]
opt-level = 2

[patch.crates-io.curve25519-dalek]
git = "https://github.com/dalek-cryptography/curve25519-dalek"
branch = "rand_core/v0.10-rc"
