[package]
name = "spake2"
version = "0.2.0"
edition = "2018"
authors = ["Brian Warner <warner@lothar.com>"]
description = "The SPAKE2 password-authenticated key-exchange algorithm."
documentation = "https://docs.rs/spake2"
homepage = "https://github.com/RustCrypto/PAKEs"
repository = "https://github.com/RustCrypto/PAKEs"
license = "MIT OR Apache-2.0"
keywords = ["crypto", "pake", "authentication"]
categories = ["cryptography", "authentication"]
exclude = [
    ".gitignore"
]

[package.metadata.release]
tag-prefix = "spake2-v"
tag-message = "(cargo-release) spake2-v{{version}}"
pre-release-commit-message = "(cargo-release) spake2-v{{version}}"
pro-release-commit-message = "(cargo-release) start next development iteration spake2-v{{version}}"

[badges]
travis-ci = { repository = "RustCrypto/PAKEs" }
is-it-maintained-issue-resolution = { repository = "RustCrypto/PAKEs" }
is-it-maintained-open-issues = { repository = "RustCrypto/PAKEs" }

[dependencies]
curve25519-dalek = "1"
rand = "0.6"
sha2 = "0.8"
hkdf = "0.7"
num-bigint = "0.2"
hex = "0.3"

[dev-dependencies]
bencher = "0.1"

[[bench]]
name = "spake2"
harness = false
